name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^1.0.1
  cupertino_icons: ^1.0.4
  flutter_bootstrap_widgets: ^1.1.0
  url_launcher: ^6.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

  flutter_application_1: any
  test: ^1.25.7
flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - assets/audio/
    - assets/